#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 29 12:31:07 2018

@author: seongjaegyeong
"""

def genPrimes():
    all_prime_collected = list()
    candidate = 1
    while True:
        candidate += 1
        for tester in all_prime_collected:
            if candidate % tester == 0:
                break
        else:
            all_prime_collected.append(candidate)
            yield candidate
            

    